import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./provider/provider";
import AppBar from "./components/appbar";
import SideBar1 from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AppBar />
          <div className="grid grid-cols-12 border">
            <div className="col-span-2">
              <SideBar1 />
            </div>
            <div className="col-span-10">
              {children}
            </div>            
          </div>
        </Provider>
      </body>
    </html>
  );
}
